### ISSUE TITLE
Home Assistant automation example

### ISSUE THREAD

**Issue by andbad** [MrSleeps/FrigateTimelapser#3]
First of all, thanks for your work.
I installed the container ad works like a charm.
Can you post an automation example for Home Assistant?
I configured the webhook and the HA address, but I can't figure out how to use it.

By(t)e

**Comment by MrSleeps** [comment]
Heya.

So there's a bit more to getting it running than just an automation.

I have rest commands setup in HA to ping the timelapse server for when I need images. These are:

```
get_office_timelapse:
  url: "https://your.timelapse.url/yourcamera/timelapse/1/0"
  method: get
get_hallway_timelapse:
  url: "https://your.timelapse.url/yourcamera/timelapse/1/0"
  method: get
```

I also have a script that calls the rest commands which is in an automation (when the front door is opened). The script I use is:

```
alias: Generate Timelapse Videos
sequence:
  - data: {}
    action: rest_command.get_office_timelapse
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - data: {}
    action: rest_command.get_hallway_timelapse
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
mode: single
icon: mdi:timelapse
```

And then finally, the automation that sends the pictures to my telegram is:

```
alias: Send Timelapse Videos To Telegram
description: ""
trigger:
  - platform: webhook
    webhook_id: "-n6J42EUtOt9843NujP9xyNOX"
    allowed_methods:
      - POST
      - PUT
    local_only: true
condition: []
action:
  - data_template:
      message: "{{trigger.json.video}}"
    enabled: true
    action: telegram_bot.send_message
  - data_template:
      url: "{{trigger.json.video}}"
    action: telegram_bot.send_video
mode: parallel
```

You don't have to use telegram, but it's what I use. For help in setting up a telegram bot and receiving messages head on over to the [Home Assistant website](https://www.home-assistant.io/integrations/telegram/).

Hope this helps!

**Comment by MrSleeps** [comment]
Heya.

So there's a bit more to getting it running than just an automation.

I have rest commands setup in HA to ping the timelapse server for when I need images. These are:

```
get_office_timelapse:
  url: "https://your.timelapse.url/yourcamera/timelapse/1/0"
  method: get
get_hallway_timelapse:
  url: "https://your.timelapse.url/yourcamera/timelapse/1/0"
  method: get
```

**Remember to change _your.timelapse.url_ and _yourcamera_ to whatever yours are.**

I also have a script that calls the rest commands which is in an automation (when the front door is opened). The script I use is:

```
alias: Generate Timelapse Videos
sequence:
  - data: {}
    action: rest_command.get_office_timelapse
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - data: {}
    action: rest_command.get_hallway_timelapse
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
mode: single
icon: mdi:timelapse
```

And then finally, the automation that sends the pictures to my telegram is:

```
alias: Send Timelapse Videos To Telegram
description: ""
trigger:
  - platform: webhook
    webhook_id: "YOURWEBHOOK"
    allowed_methods:
      - POST
      - PUT
    local_only: true
condition: []
action:
  - data_template:
      message: "{{trigger.json.video}}"
    enabled: true
    action: telegram_bot.send_message
  - data_template:
      url: "{{trigger.json.video}}"
    action: telegram_bot.send_video
mode: parallel
```
**Again, remember to change YOURWEBHOOK to your webhook!**

You don't have to use telegram, but it's what I use. For help in setting up a telegram bot and receiving messages head on over to the [Home Assistant website](https://www.home-assistant.io/integrations/telegram/).

Hope this helps!
